version: 2.1
description: "Orb to generate a version number from the git history"
orbs:
  versioning: streamroot/versioning@0.1.1
commands: 
  generate:
    parameters:
      rc_branch:
        description: Regex to determine release candidate branches
        type: string
        default: ^main$
    steps:
      - checkout
      # - versioning/generate
      - run:
          name: "Add `VERSION` environment variable to `BASH_ENV`"
          command: |
            VERSION=$CIRCLE_TAG
            if [ -z "$VERSION" ]; then
              SHA="$(git rev-parse --short HEAD)"

              VERSION="$(git describe --tags `git rev-list --tags --max-count=1` || true)"
              VERSION=${VERSION:-'0.0.0'}
              MAJOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
              MINOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
              PATCH="${VERSION%%.*}"; VERSION="${VERSION#*.}"

              if [[ "$CIRCLE_BRANCH" =~ <<parameters.rc_branch>> ]]; then
                VERSION="$MAJOR.$((MINOR+1)).$PATCH"
                echo $VERSION
              else
                VERSION="$MAJOR.$((MINOR+1)).$PATCH"
                echo $VERSION
              fi
            fi
            echo $VERSION >> ~/project/.circleci/version.txt
            cat ~/project/.circleci/version.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/version.txt

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - generate
      - attach_workspace:
          at: ~/
      - run: |
          cat ~/project/.circleci/version.txt
workflows:
  my_workflow:
    jobs:
      - build
